### ISSUE TITLE
pr2 fetches drink demo on gazebo

### ISSUE THREAD

**Issue by furushchev** [jsk-ros-pkg/jsk_demos#1149]
### working pr2.launch level
- [x] some dependencies not installed => https://github.com/jsk-ros-pkg/jsk_robot/issues/512
- [x] segfault tilt_shadow_filter => ros-perception/laser_filters#27 => https://github.com/ros-perception/laser_filters/pull/34
- [x] segfault move_base => https://github.com/jsk-ros-pkg/jsk_robot/pull/513
- [x] kinect depth confusion => PR2/pr2_common#243
- [x] wrong direction of pr2 projector => https://github.com/PR2/pr2_common/issues/227
- [ ] realtime factor is slow => now about 0.25-0.4
- [x] initial pose is not sync-ed on gazebo and rviz => https://github.com/jsk-ros-pkg/jsk_robot/pull/517
- [x] cannot move base => https://github.com/jsk-ros-pkg/jsk_robot/pull/515
### working demo launch level
- [x] different between real world and model => https://github.com/euslisp/EusLisp/pull/154 (seems easier to change model than change real world)
- [x] wrong direction of table leg => private
- [x] texture on fridge => https://github.com/jsk-ros-pkg/jsk_model_tools/pull/161
- [x] fridge is exploded => https://github.com/jsk-ros-pkg/jsk_model_tools/pull/161
- [x] cannot open door => https://github.com/jsk-ros-pkg/jsk_model_tools/pull/161
- [x] pr2 grasping is too slow => PR2/pr2_common#245
- [x] pr2 gripper action does not return results => https://github.com/jsk-ros-pkg/jsk_robot/pull/519, https://github.com/PR2/pr2_simulator/pull/115
- [x] no coffee can model => https://github.com/euslisp/EusLisp/pull/155, https://github.com/euslisp/EusLisp/pull/157
- [x] no tea pack model => https://github.com/euslisp/EusLisp/pull/156
- [x] no hamburger model => https://github.com/euslisp/EusLisp/pull/158
- [x] ignore transparency of inner shelves in fridge on gazebo => https://github.com/jsk-ros-pkg/jsk_demos/pull/1154
- [x] kinect depth image is not organized => https://github.com/ros-simulation/gazebo_ros_pkgs/pull/373
- [x] no demo launch file => https://github.com/jsk-ros-pkg/jsk_demos/pull/1155

**Comment by aginika** [comment]
https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/11 ?
https://github.com/ros-perception/laser_filters/pull/27 ?

**Comment by aginika** [comment]
rgb -> bgr プロブレム
https://github.com/PR2/pr2_common/pull/244

**Comment by aginika** [comment]
Depth nameプログラム
https://github.com/PR2/pr2_common/pull/243

**Comment by furushchev** [comment]
@aginika ありがとう

**Comment by aginika** [comment]
https://github.com/euslisp/EusLisp/issues/126

**Comment by aginika** [comment]
@furushchev tilit_shadow_filterが落ちません・・・

**Comment by aginika** [comment]
```
export ROBOT=sim
roslaunch jsk_pr2_startup pr2_gazebo_73b2.launch
```
を行っただけなのですが、これ以外にも必要でしょうか

**Comment by furushchev** [comment]
確かに落ちてます。
配列のindexに-2147483648を入れるときがあるみたいです。

-1490571
by @aginika

**Comment by furushchev** [comment]
@aginika https://github.com/furushchev/fridge これです。

**Comment by furushchev** [comment]
冷蔵庫がバラバラになってしまう時がある。

![fridge_broken](https://cloud.githubusercontent.com/assets/1901008/11649050/dafa57c2-9dbd-11e5-89a0-09f7d56ca662.png)

**Comment by furushchev** [comment]
冷蔵庫を固定してみると、ドアの把持まではうまくいきそう。

![fridge_demo](https://cloud.githubusercontent.com/assets/1901008/11649063/00bee1da-9dbe-11e5-8740-ba9e2af9d821.png)

**Comment by aginika** [comment]
- rvizでのinitial pose をinitするnodeを用意する

**Comment by aginika** [comment]
- remove this 
![gomi](https://cloud.githubusercontent.com/assets/3803922/11651015/fa3bf8a8-9dd0-11e5-95e7-bde90358e4f8.png)

**Comment by aginika** [comment]
- pr2の把持が遅い
https://github.com/PR2/pr2_common/issues/245

仮fixには
https://github.com/aginika/pr2_common/blob/speed-up-grasp/pr2_description/urdf/gripper_v0/gripper.transmission.xacro#L45
?で行けるかも。把持できるか試していないので、怪しい

**Comment by furushchev** [comment]
- pr2のstart-graspが終わらない

![grasp_fail](https://cloud.githubusercontent.com/assets/1901008/11674813/914374c4-9e67-11e5-8af0-ca31edc42d02.png)

**Comment by aginika** [comment]
stop-graspは終わる?

**Comment by furushchev** [comment]
終わる。おそらくドアハンドルに阻まれて目標に到達しないんだと思う。

**Comment by aginika** [comment]
http://answers.ros.org/question/10382/problem-picking-items-up-in-gazebo-with-pr2/
これとはべつ？
https://github.com/PR2/pr2_controllers/blob/hydro-devel/pr2_gripper_action/src/pr2_gripper_action.cpp#L212

**Comment by aginika** [comment]
start-grasp問題は上記ので解決しました。

**Comment by k-okada** [comment]
上記ので，というのは
```
<!-- Set params for sim -->
<param
name="r_gripper_controller/gripper_action_node/stall_velocity_threshold"
value="0.01" type="double"/>
<param
name="l_gripper_controller/gripper_action_node/stall_velocity_threshold"
value="0.01" type="double"/>
```
?

--
◉ Kei Okada

**Comment by aginika** [comment]
はい
その変更をhttps://github.com/jsk-ros-pkg/jsk_robot/pull/519/files
で直してくれてるはずです

**Comment by furushchev** [comment]
@aginika @k-okada みんな困ると思うのでupstreamにもPR送りました。
https://github.com/PR2/pr2_simulator/pull/115

**Comment by TheDash** [comment]
@furushchev 

If anyone else from your lab needs maintainer admin access.. let me know and I can give it to you. You guys are doing great work.

**Comment by furushchev** [comment]
Closed this issue. All issues were now solved.

**Comment by aginika** [comment]
Thanks
